fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    epel:
      repo: https://github.com/voxpupuli/puppet-epel.git
    archive:
      repo: https://github.com/voxpupuli/puppet-archive.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
  symlinks:
    lmod: "#{source_dir}"
