name    'treydock-lmod'
version '0.0.1'
source 'git://github.com/treydock/puppet-lmod.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Lmod Puppet module'
description 'Lmod Puppet module'
project_page 'http://github.com/treydock/puppet-lmod'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/gcc', '0.x'
dependency 'puppetlabs/git', '0.x'
dependency 'puppetlabs/java', '1.x'
dependency 'stahnma/epel', '0.x'
